const {chromium}=require('playwright'),fs=require('fs'),assert=require('assert');
(async()=>{
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_PATH?{executablePath:process.env.BROWSER_PATH}:{})});
try{
const page=await browser.newPage();const source=fs.readFileSync('layouts/half_horizontal.html','utf8'),css=fs.readFileSync('layouts/shared.html','utf8').match(/<style>([\s\S]*?)<\/style>/)[1]+source.match(/<style>([\s\S]*?)<\/style>/)[1],script=fs.readFileSync('layouts/shared.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
const rows=Array.from({length:15},(_,i)=>`<tr class="event-row" data-group="${i<4?'Today':'Later'}" data-index="${i}"><td>Wed 7 Oct</td><td>18:15</td><td class="event"><span class="event-name">Long event name that needs two lines to fit properly ${i}</span><span class="calendar-label">Lily’s Calendar</span></td></tr>`);
const table=r=>`<div class="next-ten"><table><colgroup><col style="width:90px"><col style="width:45px"><col></colgroup>${r.join('')}</table></div>`;
await page.setViewportSize({width:800,height:240});await page.setContent(`<style>body{margin:0}.screen{height:100vh}.layout{height:calc(100vh - 30px);box-sizing:border-box}.title_bar{height:30px}${css}</style><div class="screen"><div class="layout calendar-horizontal" data-grouping="true"><h1>Coming Up</h1><div class="calendar-columns">${table(rows.slice(0,8))}${table(rows.slice(8))}</div></div><div class="title_bar"><span class="title" data-count-template="{count} events coming up">15 events coming up</span></div></div><script>${script}</script>`);
await page.waitForTimeout(100);
const get=()=>page.evaluate(()=>({indices:Array.from(document.querySelectorAll('.event-row')).map(r=>+r.dataset.index),count:document.querySelector('.title_bar .title').textContent,bottoms:Array.from(document.querySelectorAll('table')).map(t=>t.getBoundingClientRect().bottom),footer:document.querySelector('.title_bar').getBoundingClientRect().top,labels:document.querySelectorAll('.calendar-label').length}));
let result=await get();assert(result.indices.length>0&&result.indices.length<15);assert.deepEqual(result.indices,Array.from({length:result.indices.length},(_,i)=>i));assert.equal(result.count,`${result.indices.length} events coming up`);assert(result.bottoms.every(b=>b<=result.footer));assert.equal(result.labels,result.indices.length);console.log('OG half-horizontal: chronological prefix, calendar labels, fit and footer count verified:',result.indices.length);
await page.setViewportSize({width:1600,height:500});await page.evaluate(()=>window.dispatchEvent(new Event('resize')));await page.waitForTimeout(100);result=await get();assert.equal(result.indices.length,15);console.log('Larger half-horizontal: all 15 fit.');
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
